### PR TITLE
Aggregate changes and refactor after in-person meeting

### PR DESCRIPTION
**Pull request by buske**
This pull request is intended to incorporate all of the refactoring and minor changes discussed as part of the recent in-person meeting, in preparation for the upcoming API release. I figured it would be easiest and fastest to put them all together and ask people for their input all at once. Open to comments/criticisms/alternatives.

It includes the following changes which we discussed as being part of the imminently released version:
- Replaced submitter with contact URL/name
- Removed async and email response types
- Added species field
- Changed gender to GA4GH sex specification
- Changed inheritanceMode to use HPO terms
- Refactored into separate "patient" object
- Separate geneticFeatures to genes and variants
- Moved version from URL to Accept/Content-type headers
- Removed prefixes from URLs

### CODE REVIEW

**Comment by buske** [comment]
Do we want to include using Sequence Ontology terms (#50) in this version?

**Comment by fschiettecatte** [comment]
I would want to add 'institution' to the 'contact' section, and make it optional. A name without an institution does not make sense to me.

**Comment by buske** [comment]
From Tony Brookes: 

> Spotted just one thing...
> 'Gene Name' and 'Gene Symbol' are used at different places in the spec. The latter must, of course, be the correct one.
> Also, have a million questions about things dropped or changed, but I guess I'll get up to speed in time

**Comment by buske** [comment]
+1, François. I thought that should probably be the case and wasn't sure.

**Comment by fschiettecatte** [comment]
Not sure about this but does a variant without a start make sense ?

**Comment by Relequestual** [comment]
I feel it would have been preferable to make a pull request on each issue raised. This would mean the relevant issue information could be reviewed at the same time as the change. The problem with one large pull request is we now can't merge parts of it and must merge all changes in one go.

In my mind, the disadvantages outweigh the benefits. For same reasons me make individual issues and commits, we should also make individual pull requests.

**Comment by Relequestual** [comment]
@buske Regarding https://github.com/MatchMakerExchange/mme-apis/pull/59#issuecomment-71384434 - I think so! We could set the institution to Sanger, but that could be missleading as the patient may not be related to Sanger at all.

**Comment by Relequestual** [comment]
This all looks good to me. +1 on the pull request

**Comment by fschiettecatte** [comment]
The institution should be optional, GeneMatcher will set because we have the information, but I see why it might not make sense for Decipher.

**Comment by buske** [comment]
Received the go-ahead from François, so merging.

**Comment by allasm** [comment]
Sorry for off-topic, but "+1" for "...it would have been preferable to make a pull request on each issue raised..." an "...the disadvantages outweigh the benefits...". It is now very hard to track the changes and if everything described/agreed on in an issue actually made it to the final accepted pull request.

**Comment by buske** [comment]
Agreed. Sorry about that. I tried to resolve the relevant issues and will use separate pull requests for each separate one in the future. Was just trying to resolve the massive swath of Miami topics all at once.

**Pull request merged**
