### PR TITLE
Issue #8: added test dataset of 50 patients

### PR DESCRIPTION
**Pull request by buske**
Sorry this took so long to format and convert to JSON. There is a chance that some errors were introduces in the variant positions, since I ran into a number of problems with the initial HGVS coordinates. I just wanted to get this out there as soon as I could so everyone could take a look and start adding them in preparation for a benchmark test by the end of April.

### CODE REVIEW

**Comment by Relequestual** [comment]
As soon as you can confirm you are happy that the file is 100% valid, I'll begin the merging process for the official release! =D

**Comment by buske** [comment]
@Relequestual There were two fixes to the test data records that I need to update in the file. Will be done shortly, and will let you know.

**Comment by buske** [comment]
@Relequestual, @fschiettecatte  This should be good to go. Please go ahead and start loading up these patients. Let me know if you run into any issues. Target is to be able to find the relevant matches for each patient within each of the other databases in about a week.

**Comment by Relequestual** [comment]
I previously imported the data in a manual way, so I won't have time to test that this week.

I note that there is a hgvs attribute under variant. While I agree it could be useful, it isn't in the specification. Although as this is test data, I guess that doesn't matter.

I'll take your go ahead as an OK to merge, and will finalise the release tomorrow.

**Comment by buske** [comment]
@Relequestual, sorry, I thought we had said that additional fields not part of the spec could be included where useful. I just wanted to pass through the original data for provenance, since the HGVS->genomic coordinate conversion might have introduced errors. I'm happy to remove it if you'd like.

To simplify the process of updating your test patients here's a brief summary of the changes:
- P0000079 was added
- P0001109 was deleted
- P0001135 was changed:
  - HP:0030301 -> HP:0030303
  - HP:0002472 added
  - HP:0006958 added

**Comment by fschiettecatte** [comment]
Personally I think it is fine to include extra fields that are not part of the spec, my parser just ignores them, the only difference is that I prefix mine with an underscore but that is a stylistic (pythonic) preference. I loaded all 50 into the GeneMatcher staging server.

**Comment by Relequestual** [comment]
I'm OK with that also, but we haven't specifically said this in the specification, and I think we should. It may be that we only allow additional attributes of certian objects, or at any level. Either way, we should specify this.

In addition, we should form some way of adding a human readable description for additional fields. Although I guess this would be a 1.1 issue.

I'm happy to leave it as is for now, but I'll have to alter my validation to allow for additional fields if we're agreeing that additional fields are allowed in requests.

**Comment by Relequestual** [comment]
A note on having hgvs. This is actually useful as it allows us to get an ensembl transcript (which is reauired for SNVs in our system).

**Pull request merged**
