### PR TITLE
Update documentation to include a testing section

### PR DESCRIPTION
**Pull request by Relequestual**
A proposal on how to mark requests and responses as tests / returning test patients.

### CODE REVIEW

**Comment by fschiettecatte** [comment]
Should that be 
  "test":"true" 
or 
  "test":true

**Comment by Relequestual** [comment]
I guess boolean is a better representation. I'll update.

**Comment by buske** [comment]
@Relequestual Good idea! I expanded your description a bit.

Also, because the match request already has `"test" : true` in the patient description, I removed the `?test=1` URL parameter since it seemed redundant. Is that okay? Would having it also as a GET parameter simplify anything substantially?

**Comment by sdumitriu** [comment]
Looks good, +1.

**Comment by fschiettecatte** [comment]
+1

**Comment by Relequestual** [comment]
@buske ah yes, right. I keep forgetting we're only matching one patient per request! I'll merge!

**Pull request merged**
