### PR TITLE
Fixed errors in test data

### PR DESCRIPTION
**Pull request by buske**
https://github.com/MatchmakerExchange/mme-apis/issues/93

### CODE REVIEW

**Comment by buske** [comment]
@Relequestual Or would these changes be better committed as a hotfix?

**Comment by sdumitriu** [comment]
+1 for a 1.0 hotfix.

How do we handle future changes to the standard? Change this in each pull request, or do one big update before releasing?

**Comment by Relequestual** [comment]
@buske I think a hotfix is required in this instance. With semantic versioning, in theory hotfixes would be 1.0.1 or 1.0.0.1 or something. We have opted for defining hotfixes with alpha, so 1.0a for a first hotfix.

To do this following gitflow, create a branch of hotfix/1.0a from master, then commit your changes (you can cherry pick to save time), then when we're happy, make a pull request into master. When the pull request is accepted, we tag the new release on master, and also merge the hotfix branch back into develop. Then we can delete the hotfix branch.

With our release cycle, we normally keep a release or hotfix branch open for a few days, but in the interest of creating a DOI number for papers, I figure we may not want to do that.

**Comment by Relequestual** [comment]
P.S. I edited your first comment to be the link to the issue. Personally I find that preferable to putting it in the title.

**Comment by buske** [comment]
Closed in favor of PR #104

**Pull request closed without merging**
