### PR TITLE
added sample UML sequence diagram

### PR DESCRIPTION
**Pull request by cmungall**
Is this potentially useful for clarifying things? The seq diagram can easily be extended by changing the .src, the syntax is simple

https://github.com/cmungall/mme-apis/tree/master/seq-diagram

### CODE REVIEW

**Comment by Relequestual** [comment]
I think this is useful.
I feel that it could be useful to group the actions by user performed and system performed. Although, it might be that a Use Case diagram might better discribe this (in addition), as I'm not sure grouping of actions is legal syntax / supported in a UML Sequence Diagram

**Comment by sdumitriu** [comment]
+1

**Comment by buske** [comment]
+1 I think a visualization like this is very useful. I might suggest moving Bob to the far-right and adding the optional B->Bob notification line.

**Comment by buske** [comment]
Going to count @Relequestual's approval as a +1 and merge this. We can then do PRs to edit the specifics.

**Comment by Relequestual** [comment]
Agreed!

**Pull request merged**
