### PR TITLE
Issue #48: Made 'observed' field explicitly optional

### PR DESCRIPTION
**Pull request by buske**
PR to resolve issue #48

### CODE REVIEW

**Comment by sdumitriu** [comment]
+1

**Comment by Relequestual** [comment]
I'm not convinced this solves the problem. Maybe a better solution would be to assume observed, and in stead have a field called `not_observed`. Is there a use case for having `unkown` as an option?

**Comment by fschiettecatte** [comment]
I am not keen on not_observed, I prefer 'key = value', so 'observed = yes', 'observed = no'. Unknown is GeneMatcher specific and a hold-over. We need to have it in PhenoDB because we need to record cases where it is not known is a feature is present or not for a particular disease. I don't think it makes sense for MME.

**Comment by Relequestual** [comment]
@fschiettecatte I'm not especially keen on `not_observed` either. After discussion with several colleagues, I no longer feel there's a problem with the omission of observed to mean true, while any other states should be explicit.

(linking https://github.com/MatchMakerExchange/mme-apis/issues/48 so further discussion is noted there too)

**Comment by fschiettecatte** [comment]
Well phenoDB needs it because a physician may want to record that a feature is expected for a disease but they couldn't open up the patient to check. What I am not sure about is whether it makes sense for matching. The way @buske described feature matching, the assumption is that all features are  'observed = yes', but I can see the algorithm accommodating the absence of a feature (negative weight?) and whether a feature is unknown (not quite negative weight?). As I type this I think it would be a shame to lose unknown because it would preclude a data point for people who want to play with different feature matching algorithms.

**Comment by buske** [comment]
I would agree with removing `"unknown"`. I propose `"observed"` have two states for now, `"yes"` (default) and `"no"` for this upcoming release. Should we switch it to a boolean then?

**Comment by fschiettecatte** [comment]
Boolean is ok with me.

**Comment by allasm** [comment]
We should document that "no" means "explicitly not observed" as opposed to phenoDB meaning of "we assume it is there but could not verify". IMHO it makes sense to make a boolean if in the foreseeable future we don't want to support other values such as "no in the phenoDB sense".

**Comment by buske** [comment]
@allasm We can always add `null` later for that. I'll commit something now with a clarification: `yes` is explicitly present, `no` is explicitly not present.

**Comment by sdumitriu** [comment]
Making it a boolean now will make it much harder to add other options in the future.

**Comment by buske** [comment]
Hmm, okay, I can switch this back. @fschiettecatte is fine with either. @Relequestual, any opinions? I think this is the last API issue before v1.0.

**Comment by fschiettecatte** [comment]
Thinking some more about this I agree with @sdumitriu, leaving it as a string affords us more flexibility in the future.

**Comment by cmungall** [comment]
There are ontologies with "yes" and "no"
http://bioportal.bioontology.org/search?query=Yes&commit=Search

...but even I would consider it over the top and daft to use an ontology term for this. A string/enum seems fine here

**Comment by Relequestual** [comment]
I am happy with enum of `yes` and `no`. I think it is obvious that default is when omitted, but does anyone else think that needs to be explicitly made clear?

**Comment by buske** [comment]
Explicit is always better. :) Care to commit an update to the pr with
wording that is clearer?

**Comment by Relequestual** [comment]
Done.

**Comment by buske** [comment]
Much clearer, thanks! +1 after typo corrections.

**Comment by Relequestual** [comment]
I'm reading this as having sufficiant +1s so merging.
Fixing: https://github.com/MatchMakerExchange/mme-apis/issues/48

**Pull request merged**
