### PR TITLE
Merging genomicFeatures changes into v1.0 branch

### PR DESCRIPTION
**Pull request by buske**
I believe we decided to include these changes in the v1.0 release, despite it not quite conforming to the git-flow release philosophy.

### CODE REVIEW

**Comment by fschiettecatte** [comment]
+1

**Comment by Relequestual** [comment]
Referencing issue https://github.com/MatchMakerExchange/mme-apis/issues/14

+1

**Comment by Relequestual** [comment]
Regarding our +3 required to merge policy, are we including the maker of the pull request to count as a +1 if they are part of the original MME group, like Orion? If so, we can merge this!!

**Comment by buske** [comment]
@Relequestual: did you mean to delete 'develop'?

**Comment by Relequestual** [comment]
@buske Oh gosh no! Oh dear. I totally didn't properly check what I was doing there... My bad!

**Pull request merged**
